FROM quay.io/quarkus/quarkus-micro-image:2.0

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
ENV PATH="${PATH}:/work"
COPY --chown=1001:root target/*-runner /work/samplecli

EXPOSE 8080
USER 1000

CMD ["/samplecli", "help"]
