name: Release

on:
  push:
    tags:
      - '*'

jobs:

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Maven and Docker
        env:
          VERSION: ${{ github.ref_name }}
          AR_USER: ${{ github.actor }}
          AR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          AR_URL: ghcr.io
          AR_REPO: ${{ github.repository }}
        run: |
          mvn -B -U clean verify -Pnative-container
      - name: Upload native executable
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/distributions/quarkus-java-sample-cli-*.zip
            target/distributions/quarkus-java-sample-cli-*.tgz

  build-win64:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Maven and Docker
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          mvn -B -U clean verify -Pnative-local
      - name: Upload native executable
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/distributions/quarkus-java-sample-cli-*.zip
            target/distributions/quarkus-java-sample-cli-*.tgz

  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Maven and Docker
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          mvn -B -U clean verify -Pnative-local
      - name: Upload native executable
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/distributions/quarkus-java-sample-cli-*.zip
            target/distributions/quarkus-java-sample-cli-*.tgz


