name: Test quarkus-java-sample-cli

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:

  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: compute_version
        uses: anothrNick/github-tag-action@1.66.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: fabricepipart1a
          RELEASE_BRANCHES: main
          DEFAULT_BRANCH: main
          DRY_RUN: ${{ github.event_name != 'pull_request' }}
    outputs:
      new_tag: ${{ steps.compute_version.outputs.new_tag }}

  ci:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "adopt"
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Maven and Docker
        env:
          VERSION: ${{ needs.versioning.outputs.new_tag }}
        run: |
          mvn -B -U versions:set -DnewVersion=${VERSION} &> /dev/null
          mvn -B -U clean verify -Pnative-local


  build-linux:
    needs: versioning
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.2.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Maven and Docker
        env:
          VERSION: ${{ needs.versioning.outputs.new_tag }}
        run: |
          mvn -B -U versions:set -DnewVersion=${VERSION} &> /dev/null
          mvn -B -U clean verify -Pnative-local
      - name: Upload native executable
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          files: |
            distributions/quarkus-java-sample-cli-*.zip
            distributions/quarkus-java-sample-cli-*.tgz

  build-win64:
    needs: versioning
    runs-on: windows
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.2.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Maven and Docker
        env:
          VERSION: ${{ needs.versioning.outputs.new_tag }}
        run: |
          mvn -B -U versions:set -DnewVersion=${{ env.VERSION }}
          mvn -B -U clean verify -Pnative-local
      - name: Upload native executable
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          files: |
            distributions/quarkus-java-sample-cli-*.zip
            distributions/quarkus-java-sample-cli-*.tgz




  build-macos:
    needs: versioning
    runs-on: [ macOS , ARM64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.2.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Maven and Docker
        env:
          VERSION: ${{ needs.versioning.outputs.new_tag }}
        run: |
          mvn -B -U versions:set -DnewVersion=${VERSION} &> /dev/null
          mvn -B -U clean verify -Pnative-local
      - name: Upload native executable
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          files: |
            distributions/quarkus-java-sample-cli-*.zip
            distributions/quarkus-java-sample-cli-*.tgz


