name: Test quarkus-java-sample-cli

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "adopt"
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Bump version and push tag
        id: versioning
        uses: anothrNick/github-tag-action@1.66.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: fabricepipart1a
          RELEASE_BRANCHES: main
          DEFAULT_BRANCH: main
          DRY_RUN: ${{ github.event_name != 'pull_request' }}
      - name: Build Maven and Docker
        env:
          VERSION: ${{ steps.versioning.outputs.new_tag }}
          REPO: fabricepipart/mgp-timings
        run: |
          mvn -B -U versions:set -DnewVersion=${VERSION} &> /dev/null
          mvn -B -U clean verify
